// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-8tIwxO7u7l-kfGcCSzDlhcrrhuWtjA',
    appId: '1:935066822669:web:2fda9adf7721e8defbcd44',
    messagingSenderId: '935066822669',
    projectId: 'teste-c8afe',
    authDomain: 'teste-c8afe.firebaseapp.com',
    storageBucket: 'teste-c8afe.firebasestorage.app',
    measurementId: 'G-XQTVKWCDR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCpzqgokZEzv5pF5uJoWSkbNmszLmQLYY',
    appId: '1:935066822669:android:c324cbec20695b13fbcd44',
    messagingSenderId: '935066822669',
    projectId: 'teste-c8afe',
    storageBucket: 'teste-c8afe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfGgFCKBE79sMFr7p12-rX7Rb1nW7wPQ',
    appId: '1:935066822669:ios:97092e9c879d7948fbcd44',
    messagingSenderId: '935066822669',
    projectId: 'teste-c8afe',
    storageBucket: 'teste-c8afe.firebasestorage.app',
    iosBundleId: 'com.example.automacoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQfGgFCKBE79sMFr7p12-rX7Rb1nW7wPQ',
    appId: '1:935066822669:ios:97092e9c879d7948fbcd44',
    messagingSenderId: '935066822669',
    projectId: 'teste-c8afe',
    storageBucket: 'teste-c8afe.firebasestorage.app',
    iosBundleId: 'com.example.automacoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-8tIwxO7u7l-kfGcCSzDlhcrrhuWtjA',
    appId: '1:935066822669:web:b72b5962ed96e756fbcd44',
    messagingSenderId: '935066822669',
    projectId: 'teste-c8afe',
    authDomain: 'teste-c8afe.firebaseapp.com',
    storageBucket: 'teste-c8afe.firebasestorage.app',
    measurementId: 'G-EDHVD4XQKP',
  );
}
